Repository Mo-hitto/Mo-hitto_BE, pull requests merged in 2025-05, with the labels that each got.

#6 [docs] 성공 응답 공통 처리 어드바이스 생성
  src/main/java/com/school/mohitto/config/response/GlobalResponse.java
  src/main/java/com/school/mohitto/config/response/GlobalResponseAdvice.java
Labels: :memo: docs

#7 [docs] 커스텀 예외 및 에러 코드/응답 구현
  build.gradle
  src/main/java/com/school/mohitto/exception/CustomException.java
  src/main/java/com/school/mohitto/exception/GlobalExceptionHandler.java
  src/main/java/com/school/mohitto/exception/code/ErrorCode.java
  src/main/java/com/school/mohitto/exception/dto/ErrorResponse.java
Labels: :memo: docs

#10 [docs] CI 파이프라인 구축 및 Docker-compose 적용
  .github/workflows/develop_deploy.yml
  .gitignore
  Dockerfile
  build.gradle
  compose.yml
  src/main/java/com/school/mohitto/config/response/GlobalResponse.java
  src/main/java/com/school/mohitto/config/response/GlobalResponseAdvice.java
  src/main/java/com/school/mohitto/exception/CustomException.java
  src/main/java/com/school/mohitto/exception/GlobalExceptionHandler.java
  src/main/java/com/school/mohitto/exception/code/ErrorCode.java
  src/main/java/com/school/mohitto/exception/dto/ErrorResponse.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: :memo: docs

#13 [Feat] JWT 인코딩/디코딩 기능 추가
  build.gradle
  src/main/java/com/school/mohitto/config/PropertiesConfiguration.java
  src/main/java/com/school/mohitto/domain/authentication/Token.java
  src/main/java/com/school/mohitto/domain/authentication/TokenProcessor.java
  src/main/java/com/school/mohitto/domain/authentication/TokenType.java
  src/main/java/com/school/mohitto/exception/code/ErrorCode.java
  src/main/java/com/school/mohitto/security/jwt/JwtProperties.java
  src/main/java/com/school/mohitto/security/jwt/JwtTokenProcessor.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: :sparkles: feature

#18 [Bug] docker-compose 미적용 버그 수정
  .github/workflows/develop_deploy.yml
  docker-compose.yml
  src/main/java/com/school/mohitto/controller/HealthController.java
Labels: :bug: bug

#16 [Feat] 카카오 소셜 로그인 구현
  build.gradle
  src/main/java/com/school/mohitto/config/PropertiesConfiguration.java
  src/main/java/com/school/mohitto/config/WebClientConfig.java
  src/main/java/com/school/mohitto/config/WebClientFactory.java
  src/main/java/com/school/mohitto/controller/authentication/AuthenticationController.java
  src/main/java/com/school/mohitto/domain/User.java
  src/main/java/com/school/mohitto/domain/authentication/LoginResult.java
  src/main/java/com/school/mohitto/domain/authentication/LoginWithAuthorizationCodeRequest.java
  src/main/java/com/school/mohitto/domain/authentication/OAuth2Handler.java
  src/main/java/com/school/mohitto/domain/authentication/OAuth2HandlerProvider.java
  src/main/java/com/school/mohitto/domain/authentication/OAuth2Type.java
  src/main/java/com/school/mohitto/domain/authentication/OAuth2UserInfo.java
  src/main/java/com/school/mohitto/domain/authentication/PrivateClaims.java
  src/main/java/com/school/mohitto/domain/authentication/dto/KakaoTokenResponseDto.java
  src/main/java/com/school/mohitto/domain/authentication/dto/KakaoUserInfoResponseDto.java
  src/main/java/com/school/mohitto/exception/code/ErrorCode.java
  src/main/java/com/school/mohitto/repository/UserRepository.java
  src/main/java/com/school/mohitto/security/jwt/JwtTokenProcessor.java
  src/main/java/com/school/mohitto/security/oauth2/KakaoOAuth2Handler.java
  src/main/java/com/school/mohitto/security/oauth2/KakaoOAuth2Properties.java
  src/main/java/com/school/mohitto/service/authentication/AuthenticationService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: :sparkles: feature

#19 [Feat] BaseTimeEntity 생성
  src/main/java/com/school/mohitto/config/JpaAuditingConfig.java
  src/main/java/com/school/mohitto/domain/BaseTimeEntity.java
Labels: :sparkles: feature

#25 [Bug] Swagger 버전 충돌 에러 수정 및 CustomException 메세지 에러 수정
  build.gradle
  src/main/java/com/school/mohitto/exception/CustomException.java
Labels: :bug: bug

#22 [Feat] domain entity 생성
  src/main/java/com/school/mohitto/domain/CheckboneShape.java
  src/main/java/com/school/mohitto/domain/CreatedImage.java
  src/main/java/com/school/mohitto/domain/Diagnosis.java
  src/main/java/com/school/mohitto/domain/ForeheadShape.java
  src/main/java/com/school/mohitto/domain/Gender.java
  src/main/java/com/school/mohitto/domain/Hair.java
  src/main/java/com/school/mohitto/domain/HairLength.java
  src/main/java/com/school/mohitto/domain/HairType.java
  src/main/java/com/school/mohitto/domain/Impression.java
  src/main/java/com/school/mohitto/domain/ModelImage.java
  src/main/java/com/school/mohitto/domain/Salon.java
  src/main/java/com/school/mohitto/domain/UploadImage.java
  src/main/java/com/school/mohitto/domain/User.java
  src/main/java/com/school/mohitto/domain/enums/CheckboneShapeType.java
  src/main/java/com/school/mohitto/domain/enums/ForeheadShapeType.java
  src/main/java/com/school/mohitto/domain/enums/GenderType.java
  src/main/java/com/school/mohitto/domain/enums/HairLengthType.java
  src/main/java/com/school/mohitto/domain/enums/HairTypeEnum.java
  src/main/java/com/school/mohitto/domain/enums/ImpressionType.java
  src/main/java/com/school/mohitto/domain/mapping/DiagnosisCheckboneShape.java
  src/main/java/com/school/mohitto/domain/mapping/DiagnosisForeheadShape.java
  src/main/java/com/school/mohitto/domain/mapping/DiagnosisGender.java
  src/main/java/com/school/mohitto/domain/mapping/DiagnosisHairLength.java
  src/main/java/com/school/mohitto/domain/mapping/DiagnosisHairType.java
  src/main/java/com/school/mohitto/domain/mapping/DiagnosisImpression.java
  src/main/java/com/school/mohitto/domain/mapping/UserHair.java
  src/main/java/com/school/mohitto/domain/mapping/UserSalon.java
Labels: :sparkles: feature

#30 [Feat] Swagger 인가/인증 설정 추가 및 로그아웃 기능, 엑세스 토큰 검증, 토큰 재발급 기능 개발
  src/main/java/com/school/mohitto/config/SwaggerConfig.java
  src/main/java/com/school/mohitto/controller/authentication/AuthenticationController.java
  src/main/java/com/school/mohitto/domain/authentication/BlackListToken.java
  src/main/java/com/school/mohitto/domain/authentication/LoginResult.java
  src/main/java/com/school/mohitto/domain/authentication/dto/LoginResult.java
  src/main/java/com/school/mohitto/domain/authentication/dto/LoginWithAuthorizationCodeRequest.java
  src/main/java/com/school/mohitto/domain/authentication/dto/LogoutRequest.java
  src/main/java/com/school/mohitto/domain/authentication/dto/TokenRefreshRequest.java
  src/main/java/com/school/mohitto/domain/authentication/dto/TokenRefreshResponse.java
  src/main/java/com/school/mohitto/domain/authentication/dto/TokenRefreshResult.java
  src/main/java/com/school/mohitto/domain/authentication/dto/ValidateTokenResponse.java
  src/main/java/com/school/mohitto/domain/authentication/dto/WithdrawalRequest.java
  src/main/java/com/school/mohitto/exception/code/ErrorCode.java
  src/main/java/com/school/mohitto/repository/BlackListTokenRepository.java
  src/main/java/com/school/mohitto/service/authentication/AuthenticationService.java
Labels: :sparkles: feature

#34 [feat] CORS 설정 추가
  src/main/java/com/school/mohitto/config/PropertiesConfiguration.java
  src/main/java/com/school/mohitto/config/SwaggerConfig.java
  src/main/java/com/school/mohitto/config/WebConfiguration.java
  src/main/java/com/school/mohitto/config/swagger/SwaggerConfig.java
  src/main/java/com/school/mohitto/controller/authentication/AuthenticationController.java
  src/main/java/com/school/mohitto/security/CorsProperties.java
  src/main/java/com/school/mohitto/security/interceptor/LoginInterceptor.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: :sparkles: feature

#41 [Feat] 네이버 검색 API를 활용한 미용실 검색 API 구현
  src/main/java/com/school/mohitto/config/PropertiesConfiguration.java
  src/main/java/com/school/mohitto/controller/SalonController.java
  src/main/java/com/school/mohitto/domain/Salon.java
  src/main/java/com/school/mohitto/dto/responseDTO/SalonInformationResponse.java
  src/main/java/com/school/mohitto/exception/code/ErrorCode.java
  src/main/java/com/school/mohitto/naver/NaverProperties.java
  src/main/java/com/school/mohitto/naver/dto/LocalItem.java
  src/main/java/com/school/mohitto/naver/dto/NaverLocalSearchResponse.java
  src/main/java/com/school/mohitto/repository/SalonRepository.java
  src/main/java/com/school/mohitto/service/SalonService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: :sparkles: feature

#48 [Refactor] 모델 변수 고려하여 entity값 수정
  src/main/java/com/school/mohitto/domain/CheckboneShape.java
  src/main/java/com/school/mohitto/domain/Cheekbone.java
  src/main/java/com/school/mohitto/domain/Diagnosis.java
  src/main/java/com/school/mohitto/domain/Impression.java
  src/main/java/com/school/mohitto/domain/Mood.java
  src/main/java/com/school/mohitto/domain/Sex.java
  src/main/java/com/school/mohitto/domain/enums/CheekboneType.java
  src/main/java/com/school/mohitto/domain/enums/ImpressionType.java
  src/main/java/com/school/mohitto/domain/enums/MoodType.java
  src/main/java/com/school/mohitto/domain/enums/SexType.java
  src/main/java/com/school/mohitto/domain/mapping/DiagnosisCheekbone.java
  src/main/java/com/school/mohitto/domain/mapping/DiagnosisMood.java
  src/main/java/com/school/mohitto/domain/mapping/DiagnosisSex.java
  src/main/java/com/school/mohitto/repository/CheckboneShapeRepository.java
  src/main/java/com/school/mohitto/repository/CheekboneRepository.java
  src/main/java/com/school/mohitto/repository/DiagnosisRepositorys/DiagnosisCheckboneShapeRepository.java
  src/main/java/com/school/mohitto/repository/DiagnosisRepositorys/DiagnosisCheekboneRepository.java
  src/main/java/com/school/mohitto/repository/DiagnosisRepositorys/DiagnosisGenderRepository.java
  src/main/java/com/school/mohitto/repository/DiagnosisRepositorys/DiagnosisImpressionRepository.java
  src/main/java/com/school/mohitto/repository/DiagnosisRepositorys/DiagnosisMoodRepository.java
  src/main/java/com/school/mohitto/repository/DiagnosisRepositorys/DiagnosisSexRepository.java
  src/main/java/com/school/mohitto/repository/GenderRepository.java
  src/main/java/com/school/mohitto/repository/ImpressionRepository.java
  src/main/java/com/school/mohitto/repository/MoodRepository.java
  src/main/java/com/school/mohitto/repository/SexRepository.java
  src/main/java/com/school/mohitto/service/DiagnosisService.java
Labels: :recycle: refactor

#44 [Bug] Multipart 파일 요청 데이터 크기 상향 조정
  src/main/java/com/school/mohitto/domain/enums/CheekboneType.java
  src/main/java/com/school/mohitto/domain/enums/ForeheadShapeType.java
  src/main/java/com/school/mohitto/domain/enums/HairLengthType.java
  src/main/java/com/school/mohitto/dto/requestDTO/BasicDiagnosisRequest.java
  src/main/java/com/school/mohitto/dto/requestDTO/PreferenceDiagnosisRequest.java
  src/main/java/com/school/mohitto/dto/responseDTO/DiagnosisPreferenceResponse.java
  src/main/java/com/school/mohitto/service/DiagnosisService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: :bug: bug

#59 [Refactor] isLike 속성값 고려 헤어 반환 기능 구현
  src/main/java/com/school/mohitto/controller/HairController.java
  src/main/java/com/school/mohitto/controller/MypageController.java
  src/main/java/com/school/mohitto/domain/Hair.java
  src/main/java/com/school/mohitto/dto/responseDTO/HairLikeToggleResponse.java
  src/main/java/com/school/mohitto/dto/responseDTO/HairListResponse.java
  src/main/java/com/school/mohitto/dto/responseDTO/HairResponse.java
  src/main/java/com/school/mohitto/repository/HairRepository.java
  src/main/java/com/school/mohitto/service/HairService.java
Labels: :recycle: refactor

#65 [Feat] 시뮬레이션 서비스 개발
  build.gradle
  src/main/java/com/school/mohitto/config/WebClientFactory.java
  src/main/java/com/school/mohitto/controller/SimulationController.java
  src/main/java/com/school/mohitto/domain/CreatedImage.java
  src/main/java/com/school/mohitto/dto/requestDTO/ChangeFaceRequest.java
  src/main/java/com/school/mohitto/dto/requestDTO/ChangeFaceSimulationRequest.java
  src/main/java/com/school/mohitto/dto/responseDTO/ChangeFaceResponse.java
  src/main/java/com/school/mohitto/dto/responseDTO/ChangeFaceSimulationResponse.java
  src/main/java/com/school/mohitto/repository/ModelImageRepository.java
  src/main/java/com/school/mohitto/service/SimulationService.java
Labels: :sparkles: feature
